<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_banner_content',
        'title' => 'Banner Content',
        'fields' => array (
            array (
                'key' => 'field_banner_content',
                'label' => 'Banner Content',
                'name' => 'banner_content',
                'type' => 'wysiwyg',
                'instructions' => 'Add text and images here to appear on the hero banner',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_banner_logo',
                'label' => 'Banner Logo',
                'name' => 'banner_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_banner_content_position_horizontal',
                'label' => 'Banner Content Position Horizontal',
                'name' => 'banner_content_position_horizontal',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'u-jc-l' => 'Left',
                    'u-jc-c' => 'Centre',
                    'u-jc-r' => 'Right',
                ),
                'allow_null' => 0,
                'default_value' => 'u-jc-c',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_banner_content_position_vertical',
                'label' => 'Banner Content Position Vertical',
                'name' => 'banner_content_position_vertical',
                'type' => 'button_group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'u-ai-s' => 'Top',
                    'u-ai-m' => 'Middle',
                    'u-ai-e' => 'Bottom',
                ),
                'allow_null' => 0,
                'default_value' => 'middle',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_banner_content_width',
                'label' => 'Banner Content Width',
                'name' => 'banner_content_width',
                'type' => 'text',
                'instructions' => 'You can use any unit eg. px, %, em, vw, vh, etc',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '400px',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_banner_content_style',
                'label' => 'banner content style',
                'name' => 'banner_content_style',
                'type' => 'select',
                'instructions' => 'Select Light for light back ground with dark text or select Dark for a dark background with light text',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'light' => 'Light',
                    'dark' => 'Dark',
                ),
                'default_value' => 'dark',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_banner_content_background_opacity',
                'label' => 'Banner Content Background Opacity',
                'name' => 'banner_content_background_opacity',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 50,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => 100,
                'step' => 10,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-hero-banner',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
