<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_member_info',
        'title' => 'Member Info',
        'fields' => array(
            array(
                'key' => 'field_member_name',
                'label' => 'Name',
                'name' => 'member_name',
                'type' => 'text',
                'instructions' => 'Enter the member\'s name.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_member_position',
                'label' => 'Position',
                'name' => 'member_position',
                'type' => 'text',
                'instructions' => 'Enter the member\'s position in the company.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_member_location',
                'label' => 'Location',
                'name' => 'member_location',
                'type' => 'text',
                'instructions' => 'Enter the member\'s location.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_member_bio',
                'label' => 'Bio',
                'name' => 'member_bio',
                'type' => 'wysiwyg',
                'instructions' => 'Enter a short bio for the member.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic', // Use 'basic' toolbar which includes simple formatting buttons
                'media_upload' => 0, // Disable media upload button
                'delay' => 0,
            ),

            array(
                'key' => 'field_member_email',
                'label' => 'Email',
                'name' => 'member_email',
                'type' => 'email',
                'instructions' => 'Enter the member\'s email address.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_member_tel',
                'label' => 'Tel',
                'name' => 'member_tel',
                'type' => 'text',
                'instructions' => 'Enter the member\'s telephone number.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'team_member',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
