<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_service_additional_content',
        'title' => 'Service Content',
        'fields' => array (
            array(
                'key' => 'field_service_title',
                'label' => 'Service Title',
                'name' => 'service_title',
                'type' => 'text',
                'instructions' => 'Title use on the service thumbnail.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_service_intro_content',
                'label' => 'Service Intro Content',
                'name' => 'service_intro_content',
                'type' => 'text',
                'instructions' => 'Text to be show with the service thumbnail.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_service_background_image',
                'label' => 'Service Image',
                'name' => 'service_image',
                'type' => 'image',
                'instructions' => 'Add an image for the service thumbnail',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'uploadedTo',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_service_icon',
                'label' => 'Service Icon',
                'name' => 'custom_post_icon',
                'type' => 'image',
                'instructions' => 'Add an icon to the service',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'uploadedTo',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_service_content',
                'label' => 'Service Content',
                'name' => 'service_content',
                'type' => 'wysiwyg',
                'instructions' => 'Content to be displayed on the service thumbnail. Keep it short!',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 1,
            ),
            array(
                'key'           => 'field_service_link',
                'label'         => 'Service Link',
                'name'          => 'service_link',
                'type'          => 'text',  // changed from 'url'
                'instructions'  => 'Enter a full URL (https://…) or a relative URL/path (e.g. /contact or #contact).',
                'required'      => 0,
                'conditional_logic' => 0,
                'wrapper'       => array(
                    'width' => '33',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value' => '',
                'placeholder'   => '/contact or https://example.com',
                'prepend'       => '',
                'append'        => '',
                'maxlength'     => '',
            ),
            array(
                'key' => 'field_service_link_label',
                'label' => 'Service Link Label',
                'name' => 'service_link_label',
                'type' => 'text',
                'instructions' => 'The text that appears on the link',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Find Out More',
                'placeholder' => '',
            ),
            array (
                'key' => 'field_hide_service_content_link',
                'label' => 'Hide Service Content Link',
                'name' => 'hide_service_content_link',
                'type' => 'true_false',
                'instructions' => 'This option will remove link to the content form the service menu',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Hide the link',
                'default_value' => 1,
            )
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'act_service',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;
